import { en, type TranslationKey } from './en';

/*
 * Keep the dictionaries flat and strongly typed.  The English dictionary is
 * spread first so newly-added copy remains safe until its Arabic wording is
 * added; all copy currently rendered by the app is explicitly translated
 * below.
 */
export const ar: Record<TranslationKey, string> = {
  ...en,
  languageName: 'العربية',
  'language.english': 'English',
  'language.arabic': 'العربية',
  'common.ok': 'حسناً',
  'common.cancel': 'إلغاء',
  'common.done': 'تم',
  'common.save': 'حفظ',
  'common.next': 'التالي',
  'common.back': 'رجوع',
  'common.close': 'إغلاق',
  'common.retry': 'حاول مرة أخرى',
  'common.loading': 'جارٍ التحميل…',
  'common.today': 'اليوم',
  'common.yesterday': 'أمس',
  'common.daysAgo': 'منذ {count} أيام',
  'common.month': 'شهر',
  'common.year': 'سنة',
  'tabs.home': 'الرئيسية',
  'tabs.coach': 'المدرب',
  'tabs.insights': 'الرؤى',
  'tabs.goals': 'الأهداف',
  'tabs.profile': 'الملف الشخصي',
  'home.goodMorning': 'صباح الخير',
  'home.goodAfternoon': 'مساء الخير',
  'home.goodEvening': 'مساء الخير',
  'home.feeling': 'كيف تشعر اليوم؟',
  'home.great': 'رائع',
  'home.good': 'جيد',
  'home.okay': 'حسناً',
  'home.stressed': 'متوتر',
  'home.anxious': 'قلق',
  'home.coach': 'المدرب',
  'home.expense': 'مصروف',
  'home.receipt': 'إيصال',
  'home.goals': 'الأهداف',
  'home.insights': 'الرؤى',
  'home.wellnessScore': 'مؤشر العافية المالية',
  'home.thisMonth': '+5 هذا الشهر',
  'home.todaysInsight': 'رؤية اليوم',
  'home.recentTransactions': 'المعاملات الأخيرة',
  'home.seeAll': 'عرض الكل',
  'home.noTransactions': 'لا توجد معاملات بعد',
  'home.saved': 'المدخر',
  'home.ofTotal': 'مدخر من إجمالي {amount}',
  'home.positiveChange': 'تقدم رائع نحو صندوق الطوارئ. اكتمل بنسبة 62٪!',
  'home.savingsNudge': 'ادخرت 12٪ أكثر هذا الأسبوع. استمر!',
  'home.spendingNudge': 'خطر الإنفاق الاندفاعي مرتفع — خذ نفساً قبل الشراء التالي.',
  'data.morningCoffee': 'قهوة الصباح',
  'data.salaryDeposit': 'إيداع الراتب',
  'data.onlineShopping': 'تسوق إلكتروني',
  'data.gymMembership': 'عضوية النادي',
  'data.freelancePayment': 'دفعة عمل حر',
  'data.foodDrink': 'طعام وشراب',
  'data.income': 'دخل',
  'data.shopping': 'تسوق',
  'data.health': 'صحة',
  'data.today': 'اليوم',
  'data.yesterday': 'أمس',
  'data.twoDaysAgo': 'منذ يومين',
  'data.threeDaysAgo': 'منذ 3 أيام',
  'data.fourDaysAgo': 'منذ 4 أيام',
  'data.justNow': 'الآن',
  'data.emergencyFund': 'صندوق الطوارئ',
  'data.newCar': 'سيارة جديدة',
  'data.travelFund': 'صندوق السفر',
  'data.education': 'التعليم',
  'data.dec2025': 'ديسمبر 2025',
  'data.jun2026': 'يونيو 2026',
  'data.mar2026': 'مارس 2026',
  'data.sep2026': 'سبتمبر 2026',
  'data.jan2025': 'يناير 2025',
  'month.Jan': 'يناير',
  'month.Feb': 'فبراير',
  'month.Mar': 'مارس',
  'month.Apr': 'أبريل',
  'month.May': 'مايو',
  'month.Jun': 'يونيو',
  'coach.online': 'متصل',
  'coach.suggested': 'جرّب أن تسألني…',
  'coach.ask': 'اسأل مدربك الذكي...',
  'coach.whyOverspend': 'لماذا أنفق أكثر من اللازم؟',
  'coach.saveCar': 'ساعدني في الادخار لشراء سيارة',
  'coach.analyzeSpending': 'حلل إنفاقي',
  'coach.reduceDebt': 'كيف أقلل الديون؟',
  'coach.personality': 'ما هي شخصيتي المالية؟',
  'coach.emergencyFund': 'أنشئ صندوق طوارئ',
  'coach.greeting': 'مرحباً {name}! أنا مدربك المالي الذكي. راجعت ملفك المالي وأنا مستعد لمساعدتك على بناء عادات مالية أفضل. ما الذي يشغلك اليوم؟',
  'coach.default': 'أحلل أنماطك المالية الآن. بناءً على ملفك، أرى فرصاً لتعزيز عافيتك المالية. ما المجال الذي تود التركيز عليه اليوم؟',
  'coach.overspend': 'بناءً على سجل معاملاتك، يزداد إنفاقك الاندفاعي في عطلات نهاية الأسبوع. جرّب قاعدة الـ24 ساعة: انتظر يوماً كاملاً قبل المشتريات غير الضرورية التي تتجاوز 200 جنيه.',
  'coach.save': 'هدف رائع! لخطة ادخار السيارة، أوصي بنهج 50/30/20 وفق دخلك. حوّل 2,000 جنيه شهرياً تلقائياً إلى حساب هدف مخصص.',
  'coach.debt': 'نسبة ديونك إلى دخلك صحية حالياً عند 12٪. لتسريع السداد، ركّز على الدين ذي الفائدة الأعلى أولاً.',
  'coach.spending': 'أعلى 3 فئات إنفاق لديك هي: الطعام والشراب (28٪)، التسوق (22٪)، والترفيه (15٪). خفض التسوق 30٪ سيضيف 580 جنيهاً إلى مدخراتك شهرياً.',
  'insights.efi': 'العافية المالية',
  'insights.forecast': 'التوقعات',
  'insights.nudges': 'التنبيهات',
  'insights.anomalies': 'الأنماط الشاذة',
  'insights.title': 'الرؤى المالية',
  'insights.subtitle': 'أنماط مدعومة بالذكاء الاصطناعي من سلوكك المالي',
  'insights.overall': 'العافية المالية الإجمالية',
  'insights.confidence': 'الثقة',
  'insights.impulseControl': 'التحكم\nفي الاندفاع',
  'insights.stressManagement': 'إدارة\nالتوتر',
  'insights.planning': 'التخطيط',
  'insights.monthlyOverview': 'نظرة شهرية',
  'insights.savings': 'الادخار',
  'insights.spending': 'الإنفاق',
  'insights.unusualShopping': 'ارتفاع غير معتاد في التسوق',
  'insights.unusualShoppingDesc': '420 جنيهاً فوق متوسطك — محفز اندفاع محتمل',
  'insights.weekendDining': 'نمط تناول الطعام في عطلة الأسبوع',
  'insights.weekendDiningDesc': 'تجاوز الميزانية بنسبة 35٪ في عطلات نهاية الأسبوع لثلاثة أسابيع',
  'insights.subscriptionWaste': 'اكتشاف هدر الاشتراكات',
  'insights.subscriptionWasteDesc': '3 اشتراكات نادراً ما تستخدمها بإجمالي 245 جنيهاً شهرياً',
  'insights.savingsOpportunity': 'فرصة ادخار',
  'insights.savingsOpportunityText': 'لديك 1,200 جنيه أكثر من المعتاد هذا الشهر. فكر في إضافتها إلى صندوق الطوارئ.',
  'insights.coolingOff': 'تذكير بالانتظار',
  'insights.coolingOffText': 'تصفحت 3 مواقع تسوق اليوم — خطر الاندفاع مرتفع. جرّب الانتظار 24 ساعة.',
  'insights.milestone': 'إنجاز جديد',
  'insights.milestoneText': 'حافظت على سلسلة ادخارك لمدة 12 يوماً. إنها أفضل سلسلة لك!',
  'goals.title': 'أهداف الادخار',
  'goals.dayStreak': 'سلسلة الأيام',
  'goals.totalProgress': 'التقدم الإجمالي',
  'goals.active': 'الأهداف النشطة',
  'goals.savedOfTotal': 'مدخر من إجمالي {amount}',
  'goals.target': 'الهدف: {date}',
  'goals.add': 'إضافة هدف',
  'goals.new': 'هدف ادخار جديد',
  'goals.goalName': 'اسم الهدف (مثال: صندوق الطوارئ)',
  'goals.targetAmount': 'المبلغ المستهدف (جنيه)',
  'goals.chooseIcon': 'اختر أيقونة',
  'goals.addGoal': 'إضافة هدف',
  'profile.account': 'الحساب',
  'profile.preferences': 'التفضيلات',
  'profile.security': 'الأمان',
  'profile.support': 'الدعم',
  'profile.personalInfo': 'المعلومات الشخصية',
  'profile.linkedAccounts': 'الحسابات المرتبطة',
  'profile.paymentMethods': 'طرق الدفع',
  'profile.notifications': 'الإشعارات',
  'profile.smartNudges': 'التنبيهات الذكية',
  'profile.darkMode': 'الوضع الداكن',
  'profile.language': 'اللغة',
  'profile.changePasscode': 'تغيير رمز المرور',
  'profile.biometric': 'تسجيل الدخول بالبصمة',
  'profile.privacy': 'إعدادات الخصوصية',
  'profile.help': 'مركز المساعدة',
  'profile.contact': 'التواصل مع الدعم',
  'profile.rate': 'قيّم بصيرة',
  'profile.free': 'مجاني',
  'profile.premium': 'مميز',
  'profile.premiumPlus': 'مميز+',
  'profile.memberSince': 'عضو منذ {date}',
  'profile.moneyPersonality': 'الشخصية المالية',
  'profile.retake': 'إعادة الاختبار',
  'profile.retakeTitle': 'إعادة تقييم الشخصية',
  'profile.retakeMessage': 'سيؤدي هذا إلى إعادة ضبط نتيجة شخصيتك المالية الحالية وإجراء التقييم مرة أخرى.',
  'profile.upgrade': 'ترقية',
  'profile.yourPlan': 'خطتك',
  'profile.perMonth': '/شهر',
  'profile.signOut': 'تسجيل الخروج',
  'profile.signOutQuestion': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  'profile.languageTitle': 'اختر اللغة',
  'profile.linkedMessage': 'اربط حساباتك البنكية ومزودي الدفع لتتبع المعاملات تلقائياً.\n\nقريباً لبنوك مصر ودول الخليج.',
  'profile.paymentMessage': 'إدارة البطاقات وطرق الدفع المحفوظة.\n\nقريباً.',
  'profile.passcodeMessage': 'عيّن رمزاً من 6 أرقام لتأمين حساب بصيرة.\n\nالمصادقة الحيوية متاحة أيضاً.',
  'profile.privacyMessage': 'تستخدم بصيرة بياناتك فقط لتخصيص تجربة التدريب. لا نبيع بياناتك أبداً.\n\nتُخزّن البيانات محلياً على جهازك.',
  'profile.helpMessage': '📚 الأسئلة الشائعة والدروس متاحة على:\nmindwealthai.com/help\n\nأو تواصل معنا مباشرة للحصول على دعم مخصص.',
  'profile.contactMessage': '📧 support@mindwealthai.com\n📱 واتساب: +20 100 123 4567\n\nالرد خلال 24 ساعة.',
  'profile.rateMessage': 'هل تستمتع بالتطبيق؟ يساعدنا تقييمك في الوصول إلى المزيد!\n\nاترك لنا تقييماً من 5 نجوم على App Store.',
  'profile.notNow': 'ليس الآن',
  'profile.rateNow': '⭐ قيّم الآن',
  'upgrade.title': 'طوّر رحلتك المالية',
  'upgrade.subtitle': 'اكتشف القوة الكاملة لشخصيتك المالية',
  'upgrade.monthly': 'شهري',
  'upgrade.annual': 'سنوي',
  'upgrade.save': 'وفّر {percent}٪',
  'upgrade.current': 'الحالية',
  'upgrade.stayFree': 'البقاء على الخطة المجانية',
  'upgrade.upgradeTo': 'الترقية إلى {plan}',
  'upgrade.perYear': '/سنة',
  'upgrade.perMonth': '/شهر',
  'upgrade.savings': '🎉 توفر {amount} جنيهاً سنوياً',
  'upgrade.terms': 'إلغاء في أي وقت · دفع آمن · بدون رسوم مخفية',
  'personal.title': 'المعلومات الشخصية',
  'personal.changePhoto': 'تغيير الصورة',
  'personal.fullName': 'الاسم الكامل',
  'personal.fullNamePlaceholder': 'اسمك الكامل',
  'personal.email': 'البريد الإلكتروني',
  'personal.emailPlaceholder': 'بريدك الإلكتروني',
  'personal.phone': 'رقم الهاتف',
  'personal.phonePlaceholder': '+20 100 000 0000',
  'personal.country': 'الدولة',
  'personal.currency': 'العملة',
  'personal.save': 'حفظ التغييرات',
  'personal.nameRequired': 'الاسم مطلوب',
  'personal.nameRequiredMessage': 'يرجى إدخال اسمك.',
  'personal.saved': 'تم الحفظ',
  'personal.savedMessage': 'تم تحديث معلوماتك الشخصية.',
  'onboarding.skip': 'تخطي',
  'onboarding.next': 'التالي',
  'onboarding.getStarted': 'ابدأ الآن',
  'onboarding.welcome': 'مرحباً بك في بصيرة',
  'onboarding.emailTitle': 'لنتعرف عليك',
  'onboarding.emailSubtitle': 'أدخل بريدك الإلكتروني لحفظ رحلتك المالية.',
  'onboarding.emailPlaceholder': 'البريد الإلكتروني',
  'onboarding.continue': 'متابعة',
  'onboarding.nameTitle': 'كيف نناديك؟',
  'onboarding.namePlaceholder': 'اسمك الأول',
  'onboarding.assessment': 'تقييم الشخصية المالية',
  'onboarding.question': 'السؤال {current} من {total}',
  'onboarding.result': 'شخصيتك المالية',
  'onboarding.continueToApp': 'المتابعة إلى بصيرة',
  'error.title': 'حدث خطأ ما',
  'error.message': 'واجهنا خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
  'notFound.title': 'عذراً!',
  'notFound.message': 'هذه الشاشة غير موجودة.',
  'notFound.home': 'العودة إلى الرئيسية!',
};

/** Legacy/source copy used by the assessment data which is also displayed. */
export const arExtra: Record<string, string> = {
  Understand: 'افهم',
  your: 'أموالك',
  money: 'المال',
  by: 'من خلال فهم',
  understanding: 'فهم',
  yourself: 'ذاتك',
  'Understand Your\nMoney Personality': 'افهم\nشخصيتك المالية',
  'Track Your Emotional\nFinancial Intelligence': 'تتبّع\nذكاءك المالي العاطفي',
  'Meet Your AI\nFinancial Coach': 'تعرّف على\nمدربك المالي الذكي',
  'Build Better\nFinancial Habits': 'ابنِ\nعادات مالية أفضل',
  'Discover why you spend, save, and make financial decisions the way you do.': 'اكتشف سبب إنفاقك وادخارك واتخاذك للقرارات المالية.',
  'Understand the emotions behind your financial behavior and decisions.': 'افهم المشاعر وراء سلوكك وقراراتك المالية.',
  'Receive personalized coaching, insights, and recommendations — 24/7.': 'احصل على تدريب ورؤى وتوصيات مخصصة — على مدار الساعة.',
  'Develop saving habits and long-term financial confidence, one day at a time.': 'طوّر عادات الادخار والثقة المالية طويلة المدى، يوماً بعد يوم.',
  "When you receive unexpected money, what's your first instinct?": 'عندما تحصل على مال غير متوقع، ما أول ما يخطر ببالك؟',
  "Spend it on something I've wanted": 'أنفقه على شيء أرغب فيه',
  'Save it immediately': 'أدخره فوراً',
  'Buy something to impress others': 'أشتري شيئاً لإبهار الآخرين',
  'Feel guilty and donate it': 'أشعر بالذنب وأتبرع به',
  'How do you feel when discussing money with family?': 'كيف تشعر عند مناقشة المال مع العائلة؟',
  'Anxious — I prefer not to talk about it': 'قلق — أفضل عدم التحدث عنه',
  'Obligated to help everyone financially': 'ملتزم بمساعدة الجميع مالياً',
  'Open and comfortable': 'منفتح ومرتاح',
  'It shows who has power': 'يُظهر من يملك القوة',
  'What does financial success mean to you?': 'ماذا يعني النجاح المالي لك؟',
  'Having enough to never worry again': 'امتلاك ما يكفي لعدم القلق مجدداً',
  'Living below my means, always saving': 'العيش بأقل من دخلي والادخار دائماً',
  'Driving a luxury car and nice home': 'قيادة سيارة فاخرة وامتلاك منزل جميل',
  'Being free from financial ties': 'التحرر من الالتزامات المالية',
  'When you see something expensive you want, you:': 'عندما ترى شيئاً باهظاً تريده، ماذا تفعل؟',
  'Buy it — I deserve it': 'أشتريه — فأنا أستحقه',
  'Research, wait, then decide carefully': 'أبحث وأنتظر ثم أقرر بعناية',
  'Buy it so others see my taste': 'أشتريه ليرى الآخرون ذوقي',
  'Talk myself out of it, feel relief': 'أقنع نفسي بعدم شرائه وأشعر بالارتياح',
  'Money Vigilance': 'اليقظة المالية',
  'Money Worship': 'عبادة المال',
  'Money Status': 'مكانة المال',
  'Money Avoidance': 'تجنب المال',
  'Money Obligation': 'الالتزام المالي',
  'You are careful, responsible, and private about money. You believe in saving and being prepared.': 'أنت حريص ومسؤول وتحب الخصوصية بشأن المال. تؤمن بالادخار والاستعداد.',
  'Excellent at saving and financial security': 'ممتاز في الادخار والأمان المالي',
  'May avoid spending even on important needs': 'قد تتجنب الإنفاق حتى على الاحتياجات المهمة',
  'Welcome to Bassera': 'مرحباً بك في بصيرة',
  'Smart Financial Advisory': 'استشارات مالية ذكية',
  'Tap anywhere to continue': 'اضغط في أي مكان للمتابعة',
  'Continue with Apple': 'المتابعة باستخدام Apple',
  'Continue with Google': 'المتابعة باستخدام Google',
  'Continue with Facebook': 'المتابعة باستخدام Facebook',
  'or use email or mobile': 'أو استخدم البريد الإلكتروني أو الهاتف',
  'Email or Mobile': 'البريد الإلكتروني أو الهاتف',
  'What should we call you?': 'كيف نناديك؟',
  'Bassera will personalize your experience based on your name.': 'ستخصص بصيرة تجربتك بناءً على اسمك.',
  'Your first name': 'اسمك الأول',
  'Continue': 'متابعة',
  'Question {current} of {total}': 'السؤال {current} من {total}',
  'Your Money Personality': 'شخصيتك المالية',
  Strength: 'نقاط القوة',
  'Watch Out': 'انتبه',
  'Start My Journey': 'ابدأ رحلتي',
  Skip: 'تخطي',
  Next: 'التالي',
  'Get Started': 'ابدأ الآن',
  'Your Wellness Overview': 'نظرة عامة على عافيتك',
  'Savings Rate': 'معدل الادخار',
  'Debt Ratio': 'نسبة الديون',
  'Habit Score': 'مؤشر العادات',
  'Quick Actions': 'إجراءات سريعة',
  'Smart Nudges': 'تنبيهات ذكية',
  'You saved 12% more this week. Reducing coffee spending by 20% could add 300 EGP to your Emergency Fund.': 'ادخرت 12٪ أكثر هذا الأسبوع. خفض الإنفاق على القهوة 20٪ قد يضيف 300 جنيه إلى صندوق الطوارئ.',
  'Personalized for you': 'مخصص لك',
  Category: 'الفئة',
  Amount: 'المبلغ',
  'Title (optional)': 'العنوان (اختياري)',
  'How did this feel?': 'كيف كان شعورك؟',
  'Note (optional)': 'ملاحظة (اختيارية)',
  'e.g.': 'مثال:',
  Transaction: 'معاملة',
  'Add a note...': 'أضف ملاحظة...',
  'Scan Receipt': 'مسح الإيصال',
  'Point your camera at a receipt or bill': 'وجّه الكاميرا نحو إيصال أو فاتورة',
  'Receipt preview': 'معاينة الإيصال',
  'Enter manually instead': 'الإدخال يدوياً بدلاً من ذلك',
  'Analyzing Receipt': 'تحليل الإيصال',
  'AI is extracting and categorizing items…': 'يقوم الذكاء الاصطناعي باستخراج العناصر وتصنيفها…',
  'Reading receipt': 'قراءة الإيصال',
  'Detecting items': 'اكتشاف العناصر',
  'Auto-categorizing': 'التصنيف التلقائي',
  'Calculating totals': 'حساب الإجماليات',
  'Receipt Scanned!': 'تم مسح الإيصال!',
  'AI Categorized': 'صنّفها الذكاء الاصطناعي',
  'Change category:': 'تغيير الفئة:',
  Total: 'الإجمالي',
  'Save {count} Items': 'حفظ {count} عناصر',
  'Food & Drink': 'طعام وشراب',
  Shopping: 'تسوق',
  Transport: 'مواصلات',
  Housing: 'السكن',
  Health: 'الصحة',
  Fun: 'ترفيه',
  Education: 'التعليم',
  Bills: 'فواتير',
  Savings: 'مدخرات',
  Travel: 'سفر',
  Family: 'العائلة',
  Other: 'أخرى',
  Salary: 'راتب',
  Freelance: 'عمل حر',
  Investment: 'استثمار',
  Gift: 'هدية',
  Rental: 'إيجار',
  Planned: 'مخطط',
  Impulse: 'اندفاعي',
  Routine: 'روتيني',
  Stressed: 'متوتر',
  Reward: 'مكافأة',
  Regret: 'ندم',
  'Espresso × 2': 'إسبريسو × 2',
  Croissant: 'كرواسون',
  Sandwich: 'ساندويتش',
  'Taxi Ride': 'رحلة تاكسي',
  'Toll Fee': 'رسوم الطريق',
  'T-Shirt': 'قميص',
  Shoes: 'أحذية',
  Jeans: 'جينز',
  'Build your financial future, one goal at a time': 'ابنِ مستقبلك المالي، هدفاً تلو الآخر',
  'remaining to go': 'متبقي',
  Achievements: 'الإنجازات',
  "This Week's Challenge": 'تحدي هذا الأسبوع',
  'Skip 3 impulse purchases and add the savings to your Emergency Fund.': 'تجنب 3 مشتريات اندفاعية وأضف المدخرات إلى صندوق الطوارئ.',
  'AI-powered behavioral analysis': 'تحليل سلوكي مدعوم بالذكاء الاصطناعي',
  'Emotional Financial Intelligence': 'الذكاء المالي العاطفي',
  'Your 5 EFI dimensions at a glance': 'أبعاد عافيتك المالية الخمسة في لمحة',
  'Dimension Breakdown': 'تفصيل الأبعاد',
  'Risk Indicators': 'مؤشرات المخاطر',
  'Anxiety Index': 'مؤشر القلق',
  'Spending Trigger Index': 'مؤشر محفزات الإنفاق',
  'Emotional Stability': 'الاستقرار العاطفي',
  'Low — within healthy range': 'منخفض — ضمن النطاق الصحي',
  'Moderate — monitor weekend patterns': 'متوسط — راقب أنماط عطلة الأسبوع',
  'Good — consistent over 30 days': 'جيد — مستقر خلال 30 يوماً',
  'Savings vs Spending (EGP)': 'الادخار مقابل الإنفاق (جنيه)',
  'July Predictions': 'توقعات يوليو',
  'Reducing coffee spending by 20% this month could save you 300 EGP. Over 12 months, that’s 3,600 EGP toward your Emergency Fund.': 'خفض الإنفاق على القهوة 20٪ هذا الشهر قد يوفر لك 300 جنيه. خلال 12 شهراً، ستضيف 3,600 جنيه إلى صندوق الطوارئ.',
  "Reducing coffee spending by 20% this month could save you 300 EGP. Over 12 months, that's 3,600 EGP toward your Emergency Fund.": 'خفض الإنفاق على القهوة 20٪ هذا الشهر قد يوفر لك 300 جنيه. خلال 12 شهراً، ستضيف 3,600 جنيه إلى صندوق الطوارئ.',
  'AI-powered behavioral interventions': 'تدخلات سلوكية مدعومة بالذكاء الاصطناعي',
  'Anomaly Detection': 'اكتشاف الأنماط الشاذة',
  'Unusual patterns detected by AI': 'اكتشف الذكاء الاصطناعي أنماطاً غير معتادة',
  'AI Confidence': 'ثقة الذكاء الاصطناعي',
  'View Details': 'عرض التفاصيل',
  'Egypt\nSaudi Arabia\nUAE\nKuwait\nQatar\nBahrain': 'مصر\nالسعودية\nالإمارات\nالكويت\nقطر\nالبحرين',
  'EGP — Egyptian Pound\nSAR — Saudi Riyal\nAED — UAE Dirham\nKWD — Kuwaiti Dinar': 'جنيه مصري\nريال سعودي\nدرهم إماراتي\nدينار كويتي',
  'View error details': 'عرض تفاصيل الخطأ',
  'Close error details': 'إغلاق تفاصيل الخطأ',
  'Money Personality Assessment': 'تقييم الشخصية المالية',
  'Manual Transaction Tracking': 'تتبع المعاملات يدوياً',
  'Limited AI Coach (5/day)': 'مدرب ذكي محدود (5 يومياً)',
  'Basic Insights': 'رؤى أساسية',
  'Unlimited AI Coaching': 'تدريب ذكي غير محدود',
  'Bank Integration': 'ربط الحساب البنكي',
  'Real-time EFI Tracking': 'تتبع العافية المالية لحظياً',
  'Personalized Saving Plans': 'خطط ادخار مخصصة',
  'Investment Suggestions': 'اقتراحات استثمارية',
  'Advanced Investments': 'استثمارات متقدمة',
  'Family Sharing': 'مشاركة عائلية',
  'Loan Management': 'إدارة القروض',
  'Tax Assistance': 'مساعدة ضريبية',
  'Human Advisor Sessions': 'جلسات مع مستشار بشري',
  'Most Popular': 'الأكثر شعبية',
  'All-Inclusive': 'شامل',
  'Basic expense tracking': 'تتبع أساسي للمصروفات',
  '1 financial goal': 'هدف مالي واحد',
  'Weekly EFI snapshot': 'ملخص أسبوعي للعافية المالية',
  'Limited AI coach (5 msgs/day)': 'مدرب ذكي محدود (5 رسائل يومياً)',
  'Unlimited expense tracking': 'تتبع غير محدود للمصروفات',
  'Up to 10 financial goals': 'حتى 10 أهداف مالية',
  'Full EFI dashboard': 'لوحة العافية المالية الكاملة',
  'Receipt scanning & OCR': 'مسح الإيصالات والتعرف الضوئي',
  'Weekly behavioral report': 'تقرير سلوكي أسبوعي',
  '1-on-1 human advisor': 'مستشار بشري فردي',
  'Custom investment portfolio': 'محفظة استثمارية مخصصة',
  'Everything in Premium': 'كل ما في الخطة المميزة',
  '1-on-1 certified advisor': 'مستشار معتمد فردي',
  'Unlimited financial goals': 'أهداف مالية غير محدودة',
  'Priority support 24/7': 'دعم أولوية على مدار الساعة',
  'Family account (up to 5)': 'حساب عائلي (حتى 5 أفراد)',
  'Tax optimization hints': 'نصائح لتحسين الضرائب',
};