export const en = {
  languageName: 'English',
  'language.english': 'English',
  'language.arabic': 'العربية',
  'common.ok': 'OK',
  'common.cancel': 'Cancel',
  'common.done': 'Done',
  'common.save': 'Save',
  'common.next': 'Next',
  'common.back': 'Back',
  'common.close': 'Close',
  'common.retry': 'Try Again',
  'common.loading': 'Loading…',
  'common.today': 'Today',
  'common.yesterday': 'Yesterday',
  'common.daysAgo': '{count} days ago',
  'common.month': 'month',
  'common.year': 'year',
  'tabs.home': 'Home',
  'tabs.coach': 'Coach',
  'tabs.insights': 'Insights',
  'tabs.goals': 'Goals',
  'tabs.profile': 'Profile',
  'home.goodMorning': 'Good morning',
  'home.goodAfternoon': 'Good afternoon',
  'home.goodEvening': 'Good evening',
  'home.feeling': 'How are you feeling today?',
  'home.great': 'Great',
  'home.good': 'Good',
  'home.okay': 'Okay',
  'home.stressed': 'Stressed',
  'home.anxious': 'Anxious',
  'home.coach': 'Coach',
  'home.expense': 'Expense',
  'home.receipt': 'Receipt',
  'home.goals': 'Goals',
  'home.insights': 'Insights',
  'home.wellnessScore': 'Financial Wellness Score',
  'home.thisMonth': '+5 this month',
  'home.todaysInsight': "Today's Insight",
  'home.recentTransactions': 'Recent Transactions',
  'home.seeAll': 'See All',
  'home.noTransactions': 'No transactions yet',
  'home.saved': 'Saved',
  'home.ofTotal': 'saved of {amount} total',
  'home.positiveChange': 'Great progress toward your Emergency Fund. 62% complete!',
  'home.savingsNudge': 'You saved 12% more this week. Keep it up!',
  'home.spendingNudge': 'Impulse spending risk elevated — take a breath before your next purchase.',
  'data.morningCoffee': 'Morning Coffee',
  'data.salaryDeposit': 'Salary Deposit',
  'data.onlineShopping': 'Online Shopping',
  'data.gymMembership': 'Gym Membership',
  'data.freelancePayment': 'Freelance Payment',
  'data.foodDrink': 'Food & Drink',
  'data.income': 'Income',
  'data.shopping': 'Shopping',
  'data.health': 'Health',
  'data.today': 'Today',
  'data.yesterday': 'Yesterday',
  'data.twoDaysAgo': '2 days ago',
  'data.threeDaysAgo': '3 days ago',
  'data.fourDaysAgo': '4 days ago',
  'data.justNow': 'Just now',
  'data.emergencyFund': 'Emergency Fund',
  'data.newCar': 'New Car',
  'data.travelFund': 'Travel Fund',
  'data.education': 'Education',
  'data.dec2025': 'Dec 2025',
  'data.jun2026': 'Jun 2026',
  'data.mar2026': 'Mar 2026',
  'data.sep2026': 'Sep 2026',
  'data.jan2025': 'Jan 2025',
  'month.Jan': 'Jan',
  'month.Feb': 'Feb',
  'month.Mar': 'Mar',
  'month.Apr': 'Apr',
  'month.May': 'May',
  'month.Jun': 'Jun',
  'coach.online': 'Online',
  'coach.suggested': 'Try asking me…',
  'coach.ask': 'Ask your AI coach...',
  'coach.whyOverspend': 'Why do I overspend?',
  'coach.saveCar': 'Help me save for a car',
  'coach.analyzeSpending': 'Analyze my spending',
  'coach.reduceDebt': 'How to reduce debt?',
  'coach.personality': 'What is my money personality?',
  'coach.emergencyFund': 'Build an emergency fund',
  'coach.greeting': "Hi {name}! I'm your AI Financial Coach. I've reviewed your financial profile and I'm ready to help you build better financial habits. What's on your mind today?",
  'coach.default': "I'm analyzing your financial patterns now. Based on your profile, I can see opportunities to strengthen your financial wellness. What specific area would you like to focus on today?",
  'coach.overspend': 'Based on your transaction history, your impulse spending tends to spike on weekends. This is linked to emotional spending triggers — particularly stress relief. Try the 24-hour rule: wait a full day before non-essential purchases over 200 EGP. Your Money Profile suggests you benefit from structured cooling-off periods.',
  'coach.save': 'Great goal! For a car savings plan, I recommend the 50/30/20 approach adapted for your income. Set up an automatic transfer of 2,000 EGP monthly to a dedicated goal account. At your current income, you could reach your car goal in 18-24 months. Want me to create a personalized savings plan?',
  'coach.debt': "Your debt-to-income ratio is currently healthy at 12%. To accelerate payoff, use the avalanche method — focus extra payments on the highest-interest debt first. This could save you significant interest over time. I've identified 3 areas where you can redirect 1,500 EGP monthly toward debt.",
  'coach.spending': 'Your top 3 spending categories are: Food & Drink (28%), Shopping (22%), and Entertainment (15%). Compared to last month, shopping increased by 18% — this correlates with high-stress periods in your mood log. Reducing shopping by 30% would add 580 EGP to your savings monthly.',
  'insights.efi': 'EFI',
  'insights.forecast': 'Forecast',
  'insights.nudges': 'Nudges',
  'insights.anomalies': 'Anomalies',
  'insights.title': 'Financial Insights',
  'insights.subtitle': 'AI-powered patterns from your financial behavior',
  'insights.overall': 'Overall EFI',
  'insights.confidence': 'Confidence',
  'insights.impulseControl': 'Impulse\nControl',
  'insights.stressManagement': 'Stress\nMgmt',
  'insights.planning': 'Planning',
  'insights.monthlyOverview': 'Monthly Overview',
  'insights.savings': 'Savings',
  'insights.spending': 'Spending',
  'insights.unusualShopping': 'Unusual shopping spike',
  'insights.unusualShoppingDesc': '420 EGP above your average — possible impulse trigger',
  'insights.weekendDining': 'Weekend dining pattern',
  'insights.weekendDiningDesc': 'Consistent 35% over-budget on weekends for 3 weeks',
  'insights.subscriptionWaste': 'Subscription waste detected',
  'insights.subscriptionWasteDesc': '3 rarely-used subscriptions totaling 245 EGP/month',
  'insights.savingsOpportunity': 'Savings opportunity',
  'insights.savingsOpportunityText': 'You have 1,200 EGP more than usual this month. Consider adding to your Emergency Fund.',
  'insights.coolingOff': 'Cooling-off reminder',
  'insights.coolingOffText': "You've browsed 3 shopping sites today — impulse risk is elevated. Try a 24-hour wait.",
  'insights.milestone': 'Milestone reached',
  'insights.milestoneText': "You've maintained your savings streak for 12 days. Your best streak ever!",
  'goals.title': 'Savings Goals',
  'goals.dayStreak': 'Day Streak',
  'goals.totalProgress': 'Total Progress',
  'goals.active': 'Active Goals',
  'goals.savedOfTotal': 'saved of {amount} total',
  'goals.target': 'Target: {date}',
  'goals.add': 'Add Goal',
  'goals.new': 'New Savings Goal',
  'goals.goalName': 'Goal name (e.g. Emergency Fund)',
  'goals.targetAmount': 'Target amount (EGP)',
  'goals.chooseIcon': 'Choose an icon',
  'goals.addGoal': 'Add Goal',
  'profile.account': 'Account',
  'profile.preferences': 'Preferences',
  'profile.security': 'Security',
  'profile.support': 'Support',
  'profile.personalInfo': 'Personal Information',
  'profile.linkedAccounts': 'Linked Accounts',
  'profile.paymentMethods': 'Payment Methods',
  'profile.notifications': 'Notifications',
  'profile.smartNudges': 'Smart Nudges',
  'profile.darkMode': 'Dark Mode',
  'profile.language': 'Language',
  'profile.changePasscode': 'Change Passcode',
  'profile.biometric': 'Biometric Login',
  'profile.privacy': 'Privacy Settings',
  'profile.help': 'Help Center',
  'profile.contact': 'Contact Support',
  'profile.rate': 'Rate Bassera',
  'profile.free': 'Free',
  'profile.premium': 'Premium',
  'profile.premiumPlus': 'Premium+',
  'profile.memberSince': 'Member since {date}',
  'profile.moneyPersonality': 'Money Personality',
  'profile.retake': 'Retake',
  'profile.retakeTitle': 'Retake Assessment',
  'profile.retakeMessage': 'This will reset your current Money Personality result and run the assessment again.',
  'profile.upgrade': 'Upgrade',
  'profile.yourPlan': 'Your Plan',
  'profile.perMonth': '/month',
  'profile.signOut': 'Sign Out',
  'profile.signOutQuestion': 'Are you sure you want to sign out?',
  'profile.languageTitle': 'Choose language',
  'profile.linkedMessage': 'Connect your bank accounts and payment providers for automatic transaction tracking.\n\nComing soon for Egypt & GCC banks.',
  'profile.paymentMessage': 'Manage saved cards and payment methods.\n\nComing soon.',
  'profile.passcodeMessage': 'Set a 6-digit PIN to secure your Bassera account.\n\nBiometric authentication is also available.',
  'profile.privacyMessage': 'Bassera only uses your data to personalize your coaching experience. We never sell your data.\n\nData stored locally on your device.',
  'profile.helpMessage': '📚 FAQs, tutorials, and guides are available at:\nmindwealthai.com/help\n\nOr contact us directly for personalized support.',
  'profile.contactMessage': '📧 support@mindwealthai.com\n📱 WhatsApp: +20 100 123 4567\n\nResponse within 24 hours.',
  'profile.rateMessage': 'Enjoying the app? Your review helps us reach more people!\n\nLeave us a 5-star review on the App Store.',
  'profile.notNow': 'Not Now',
  'profile.rateNow': '⭐ Rate Now',
  'upgrade.title': 'Upgrade Your Financial Journey',
  'upgrade.subtitle': 'Unlock the full power of your money personality',
  'upgrade.monthly': 'Monthly',
  'upgrade.annual': 'Annual',
  'upgrade.save': 'Save {percent}%',
  'upgrade.current': 'Current',
  'upgrade.stayFree': 'Stay on Free Plan',
  'upgrade.upgradeTo': 'Upgrade to {plan}',
  'upgrade.perYear': '/year',
  'upgrade.perMonth': '/month',
  'upgrade.savings': '🎉 You save {amount} EGP per year',
  'upgrade.terms': 'Cancel anytime · Secure payment · No hidden fees',
  'personal.title': 'Personal Information',
  'personal.changePhoto': 'Change Photo',
  'personal.fullName': 'FULL NAME',
  'personal.fullNamePlaceholder': 'Your full name',
  'personal.email': 'EMAIL ADDRESS',
  'personal.emailPlaceholder': 'Your email address',
  'personal.phone': 'PHONE NUMBER',
  'personal.phonePlaceholder': '+20 100 000 0000',
  'personal.country': 'COUNTRY',
  'personal.currency': 'CURRENCY',
  'personal.save': 'Save Changes',
  'personal.nameRequired': 'Name required',
  'personal.nameRequiredMessage': 'Please enter your name.',
  'personal.saved': 'Saved',
  'personal.savedMessage': 'Your personal information has been updated.',
  'onboarding.skip': 'Skip',
  'onboarding.next': 'Next',
  'onboarding.getStarted': 'Get Started',
  'onboarding.welcome': 'Welcome to Bassera',
  'onboarding.emailTitle': 'Let’s get to know you',
  'onboarding.emailSubtitle': 'Enter your email to save your financial journey.',
  'onboarding.emailPlaceholder': 'Email address',
  'onboarding.continue': 'Continue',
  'onboarding.nameTitle': 'What should we call you?',
  'onboarding.namePlaceholder': 'Your first name',
  'onboarding.assessment': 'Money Personality Assessment',
  'onboarding.question': 'Question {current} of {total}',
  'onboarding.result': 'Your Money Personality',
  'onboarding.continueToApp': 'Continue to Bassera',
  'error.title': 'Something went wrong',
  'error.message': 'We encountered an unexpected error. Please try again.',
  'notFound.title': 'Oops!',
  'notFound.message': "This screen doesn't exist.",
  'notFound.home': 'Go to home screen!',
} as const;

export type TranslationKey = keyof typeof en;